### ISSUE TITLE
Azerbaijan actor not running since 22.4.2020

### ISSUE THREAD

**Issue by Lucie20** [apifytech/covid-19#11]
Last data are from 22.4. (today 30.4.) needs to be checked, the source URL is updated
{
  "country": "Azerbaijan",
  "infected": 1518,
  "recovered": 907,
  "deceased": 20,
  "tested": 108221,
  "sourceUrl": "https://koronavirusinfo.az/az/page/statistika/azerbaycanda-cari-veziyyet",
  "lastUpdatedAtApify": "2020-04-22T13:50:08.000Z",
  "lastUpdatedAtSource": "N/A"
}

**Comment by zpelechova** [comment]
Solved.
