### ISSUE TITLE
Brazil actor not running

### ISSUE THREAD

**Issue by Lucie20** [apifytech/covid-19#117]
the last update for Brazil 5 hours ago, needs to be checked @pocesar 
thank you

**Comment by pocesar** [comment]
from 4AM to 9:30AM (UTC) the website was completely down before then the JSON payload was missing, the latest data seems to be correct (from 2020-05-16T23:26:24.937Z)

**Comment by pocesar** [comment]
after further inspection, the data is being updated by them (the numbers), but their "updatedAt" is remaining the same.
