### ISSUE TITLE
Phillipines actor not running

### ISSUE THREAD

**Issue by Lucie20** [apifytech/covid-19#118]
the actor is not running or the last 11 hours, needs to be checked

**Comment by katacek** [comment]
The source data were available on gdrive - see link in readme - but they are no longer there..

**Comment by remyoucef** [comment]
@katacek if you want to fix this here is a new source http://www.covid19.gov.ph/, if you don't let me know.

**Comment by katacek** [comment]
@remyoucef if you can, please, fix it, thanks!

**Comment by remyoucef** [comment]
@katacek ok, we'll fix it.

**Comment by zpelechova** [comment]
Thx!
