### ISSUE TITLE
Finland aggregator not linked to source actor

### ISSUE THREAD

**Issue by Lucie20** [apifytech/covid-19#12]
update JSON for aggregator, actor attributes changed and are not matched to the aggregator attributes

**Comment by Lucie20** [comment]
link to the JSON https://github.com/apifytech/covid-19/blob/master/world/src/transform-schema.json

**Comment by zpelechova** [comment]
Working on it.

**Comment by Lucie20** [comment]
@zpelechova please add infected in the overview table number missing, thank you
