### ISSUE TITLE
DK - columns shifted since 17th May 2020

### ISSUE THREAD

**Issue by clementlefevre** [apifytech/covid-19#123]
Since 05.17.2020 the column are shifted :

[apify](https://api.apify.com/v2/datasets/Ugq8cNqnhUSjfJeHr/items?format=json&clean=1) :
```
tested: 490782,
infected: 412051,
recovered: 11117,
deceased: 9416,
sourceUrl: "https://www.ssi.dk/aktuelt/sygdomsudbrud/coronavirus",
lastUpdatedAtApify: "2020-05-20T08:00:00.000Z",
readMe: "https://apify.com/tugkan/covid-dk"
}
```

vs [https://www.sst.dk/da/corona/tal-og-overvaagning](https://www.sst.dk/da/corona/tal-og-overvaagning) :

  | Number of samples 1 | People tested 2 | Infected persons 3 | Posted 4 | Of which hospitalized on intensive | Of which hospitalized on intensive and in respirator | Transient infections 5 | Deaths 6 | Deaths in% of infected
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Denmark | 490782 | 412051 | 11117 | 127 | 25 | 16 | 9536 | 554 | 5.0

`

**Comment by zpelechova** [comment]
Almost done, also the page has changed. Thanks for the info.

**Comment by zpelechova** [comment]
The actor is set to get correct numbers again.
