### ISSUE TITLE
France update source link, actor not running since 23.4.

### ISSUE THREAD

**Issue by Lucie20** [apifytech/covid-19#13]
update the source link to -> https://www.santepubliquefrance.fr/maladies-et-traumatismes/maladies-et-infections-respiratoires/infection-a-coronavirus/articles/infection-au-nouveau-coronavirus-sars-cov-2-covid-19-france-et-monde

the last run of the actor ->  "lastUpdatedAtSource": "2020-04-23T00:00:00.000Z", data not actual, need to be checked

**Comment by drobnikj** [comment]
I changed the source to https://dashboard.covid19.data.gouv.fr/
It should work now, source code is still in repo https://github.com/drobnikj/covid-france

**Comment by Lucie20** [comment]
@drobnikj France is not correct in the actor on COVID web and in the table https://apify.com/covid-19, could you please update the JSON for the page? thank you

**Comment by zpelechova** [comment]
I will do it.

**Comment by zpelechova** [comment]
I recopied the code from @drobnikj and rebuilt.
