### ISSUE TITLE
Slovakia source link

### ISSUE THREAD

**Issue by Lucie20** [apifytech/covid-19#134]
update source link on Apify covid page to https://experience.arcgis.com/experience/3430195d620344c38e81d307c252c14f/

**Comment by zpelechova** [comment]
Will do.

**Comment by remyoucef** [comment]
Hey @zpelechova, are you still working on this?

**Comment by zpelechova** [comment]
Checking if it means just changing the page in info directory. If yes, done.

**Comment by remyoucef** [comment]
Cool!
