### ISSUE TITLE
Slovenia - wrong number (new page?)

### ISSUE THREAD

**Issue by zpelechova** [apifytech/covid-19#139]

**Comment by zpelechova** [comment]
Possibly here?

**Comment by remyoucef** [comment]
Working on it.

**Comment by remyoucef** [comment]
I think that nothing wrong with the actor.

**Comment by zpelechova** [comment]
But it returns 9 as number of infected. @remyoucef

**Comment by laidihalim** [comment]
Yes @zpelechova, 9 is the daily infected number, there is nothing wrong with actor, from the beginning the actor return only the daily cases.
The total cases are available as xlsx  format in file this page:
https://www.gov.si/en/topics/coronavirus-disease-covid-19/actual-data/
I can update it to this source.

**Comment by zpelechova** [comment]
I also got to this site: https://covid-19.sledilnik.org/sl/stats but generally yes, we would like to get the sum number, not only today. Thx.

**Comment by remyoucef** [comment]
Fixed and ready for merge #141
