### ISSUE TITLE
Iran validate source data descriptions

### ISSUE THREAD

**Issue by Lucie20** [apifytech/covid-19#14]
Anybody with Iran language knowledge? 
Validate the descriptions, not sure we have the numbers correctly assigned to the right attributes...
Actor:
  "infected": 92584,
  "tested": "N/A",
  **"recovered": 72439,**
  "deceased": 5877,
  "newCases": 1112,
Web with translator:
Corona's latest statistics in Iran
Patients today 1,112
Definite patients 92,584
**Improved 72,439**
Deaths 5,877

**Comment by remyoucef** [comment]
It's **recovered** (in Persian "بهبود یافتگان"), the data is correct.

**Comment by zpelechova** [comment]
Thank you, Youcef. I am closing the issue then.
