### ISSUE TITLE
Palestine source data not available

### ISSUE THREAD

**Issue by Lucie20** [apifytech/covid-19#21]
data on the source page any more available, find a new source or switch off the actor and remove it from web (or keep only history data on the web, remove the latest link and remove from the table)

**Comment by remyoucef** [comment]
We can't find a new source but the old embedded source still working. Should we keep using it or turn off the actor?

**Comment by zpelechova** [comment]
Abdelhalim will fix this one.

**Comment by zpelechova** [comment]
Done.
