### ISSUE TITLE
Slovakia data not actual

### ISSUE THREAD

**Issue by Lucie20** [apifytech/covid-19#23]
there is a new version of the source data chart, the actor needs to be corrected
new dashboard here https://experience.arcgis.com/experience/3430195d620344c38e81d307c252c14f/
update as well the source links in the actor and covid web

**Comment by laster04** [comment]
I'am on it

**Comment by remyoucef** [comment]
Can we close this?

**Comment by zpelechova** [comment]
Closing, merged and done.
