### ISSUE TITLE
Czech critical key value is zero

### ISSUE THREAD

**Issue by RajceP** [apifytech/covid-19#40]
The value of critical patiens is zero.

`"critical": 0,`

It is wrong.

It is right in daily hospitalizationData, though (67).

`[ "2020-04-30T00:00:00.000Z", 344, 67, "0,1948", 667, "0,572" ]`

**Comment by zpelechova** [comment]
Hey, can you provide decription of the issue? I just checked  both datasets and seems ok to me.

**Comment by RajceP** [comment]
Sorry, I updated the description.

**Comment by Lucie20** [comment]
could you please close the issue, if solved? thank you

**Comment by RajceP** [comment]
The issue hasn't been solved yet.

**Comment by zpelechova** [comment]
Sorry, fixed now :)
