### ISSUE TITLE
Saudi data not actual 

### ISSUE THREAD

**Issue by FahadAlMutairi5** [apifytech/covid-19#43]
The source of saudi data change the data value but the apify not updated

**Comment by FahadAlMutairi5** [comment]
kindly reminder the bug also today

**Comment by Lucie20** [comment]
we are working on the correction, thank you for letting us know

**Comment by Laidi-abdelhalim** [comment]
I'll fix it.

**Comment by katacek** [comment]
fix #59  including all cities

**Comment by FahadAlMutairi5** [comment]
thanks all , but FYI the deceased key in each city undefined right know

**Comment by FahadAlMutairi5** [comment]
EX. 
now : 
مكة المكرمة: {
infected: "7410",
active: " 5537",
recovered: "1778"
}
but it should like that : 
مكة المكرمة: {
infected: "7410",
active: " 5537",
recovered: "1778",
deceased: "95"
}

**Comment by FahadAlMutairi5** [comment]
I think you need to change this line in main.js 
citiesArray.forEach(x =>
        {
            data[x]['infected'] = $(`strong:contains(${x})`).closest('p').find("span[style='color:#e60000']").eq(0).text().replace(',','');
            data[x]['active'] = $(`strong:contains(${x})`).closest('p').find("span[style='color:#e69800']").eq(0).text().replace(',','');
            data[x]['recovered'] = $(`strong:contains(${x})`).closest('p').find("span[style='color:#70a800']").eq(0).text().replace(',','');
        })

**Comment by katacek** [comment]
Thanks, you are right. It is because I cannot see the deceased key for each city on the website (https://covid19.moh.gov.sa/en/). Before, we took the data from different endpoint (including deceased key) but those data were not actual.
If I am wrong and the deceased key can be found on the website, it can be fixed easily.

**Comment by FahadAlMutairi5** [comment]
yes you are right, but actual the deceased you can find it if you click on the name of city 
<div id="ember492" class="flex-fix allow-shrink indicator-center-text responsive-text flex-vertical ember-view"><svg class="responsive-text-group" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0.000002302537268406013 -0.15551595389842987 161.9050750732422 160.01295471191406" width="68" height="67.20531098539">
  <g class="responsive-text-icon">
    
  </g>

  <g class="responsive-text-label">
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 -152.9375 195.203125 192.90625" height="160" width="161.90507046816785">
      <text vector-effect="non-scaling-stroke" style="fill: rgb(255, 255, 255); stroke-width: 2; font-size: 160px; line-height: normal;">**95**</text>
    </svg>
  </g>
</svg></div>

![Screen Shot 1441-09-14 at 11 05 52 PM](https://user-images.githubusercontent.com/47291969/81340105-f3af7a80-90b7-11ea-9f81-c253a2ca6860.png)

**Comment by FahadAlMutairi5** [comment]
after you select the name of city you can find the deceased of this city in الوفيات section
