### ISSUE TITLE
China data is wrong 

### ISSUE THREAD

**Issue by anishtr4** [apifytech/covid-19#50]
China data seems to be wrong please look into this, it seems to be quick fix.

**Comment by laidihalim** [comment]
I'm working on it

**Comment by ejc123** [comment]
The source has a sub-object with global stats.  The values seem to be a concatenation of confirmedCount, curedCount, deadCount from the results and the contained globalStatistics object

**Comment by zpelechova** [comment]
Fixed by the author.
