### ISSUE TITLE
Philippines data alternates every other update (unreliable?)

### ISSUE THREAD

**Issue by fractaal** [apifytech/covid-19#66]
![image](https://user-images.githubusercontent.com/19900120/81361791-e6bf7500-9111-11ea-990a-39b8065ea2d1.png)

Data retrieved from Philippines API shows deaths, infected and recovered numbers jumping up and down every other update

**Comment by katacek** [comment]
thank you, I will check it.

**Comment by katacek** [comment]
increased time for csv download, hopefully fixed
