### ISSUE TITLE
Norway - missing number for infected

### ISSUE THREAD

**Issue by zpelechova** [apifytech/covid-19#80]

**Comment by remyoucef** [comment]
We're working on it.

**Comment by laidihalim** [comment]
Norway tested value not available anymore in source https://www.fhi.no/en/id/infectious-diseases/coronavirus/daily-reports/daily-reports-COVID19/.
Should we calculate its value from "Laboratory analysis results for SARS-CoV-2..." table: Totale of Negative + Positive values
Or get the value from https://www.fhi.no/en/id/infectious-diseases/coronavirus/

**Comment by remyoucef** [comment]
The English version is not updated frequently. Check this https://www.fhi.no/sv/smittsomme-sykdommer/corona/

**Comment by laidihalim** [comment]
Thank you @remyoucef , this source shows the frequently updated data.

**Comment by zpelechova** [comment]
Great work, guys!
