### ISSUE TITLE
Latvia doesn't return any data

### ISSUE THREAD

**Issue by zpelechova** [apifytech/covid-19#83]

**Comment by remyoucef** [comment]
We'll fix it.

**Comment by zpelechova** [comment]
Run failed: https://my.apify.com/view/runs/KQyHFuCdhYneg83n9

**Comment by remyoucef** [comment]
Perhaps failed due to the proxy quota on the associated account. Can you check please?

**Comment by Lucie20** [comment]
corrected

**Comment by zpelechova** [comment]
Right, thanks Youcef.

**Comment by remyoucef** [comment]
Good, thanks all.
